title: interTwin DTE
description: Docs for the interTwin DTE components
theme: jekyll-theme-minimal

url: https://interTwin-eu.github.io

#aux_links:
#  Template Repository: https://github.com/interTwin-eu/documentation

favicon_ico: "favicon.ico"

nav_external_links:
  - title: interTwin on GitHub
    url: https://github.com/interTwin-eu/
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: interTwin project
    url: https://www.intertwin.eu/
    hide_icon: false # set to true to hide the external link icon - defaults to false

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.1.0"
